coin = uint
epoch = uint

header =
  [ header_body
  , body_signature : $kes_signature
  , test : coin / null
  , withComment : null ; This is a comment
  ]

header_body = [
  issuer : text
]

$kes_signature = bytes .size 32
